fversion: "3.7"
services:
  db:
    image: svyat94/db
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: svyat94/backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: svyat94/frontend
    volumes:
      - frontend_value:/app/build/

  nginx:
    image: svyat94/nginx
    ports:
      - "8000:80"
      #- "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docs/:/usr/share/nginx/html/api/docs/
      - frontend_value:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      #- ./certbot/conf:/etc/nginx/ssl
      #- ./certbot/data:/usr/share/nginx/html/letsencrypt

    depends_on:
      - backend
      - frontend
      #certbot:
      #image: certbot/certbot:latest
      #command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email vinogradov.s94@yandex.ru --agree-tos --no-eff-email -d svyat94foodgram.ddns.net
      #volumes:
      #- ./certbot/conf:/etc/letsencrypt
      #- ./certbot/logs:/var/log/letsencrypt
      #- ./certbot/data:/usr/share/nginx/html/letsencrypt

volumes:
  static_value:
  media_value:
  frontend_value:


