# Generated by Django 4.0 on 2023-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Игредиенты для рецепта', related_name='recipes', through='recipes.RecipeIngredients', to='recipes.Ingredient', verbose_name='Игредиенты для рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Тег рецепта', related_name='recipes', through='recipes.RecipeTags', to='recipes.Tag', verbose_name='Теги рецепта'),
        ),
    ]
