# Generated by Django 4.0 on 2023-09-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите единицу измерения(гр/кг/мл/шт)', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
